# Generated by Django 4.1.3 on 2022-12-09 06:15

import ckeditor.fields
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('css_name', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Bayern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Bayern', max_length=100)),
                ('logo', models.ImageField(default='logos/bayern_logo.png', null=True, upload_to='logos')),
                ('color', models.CharField(max_length=50, null=True)),
                ('alt_color', models.CharField(max_length=50, null=True)),
                ('manager', models.CharField(max_length=100, null=True)),
                ('fb_link', models.CharField(max_length=100, null=True)),
                ('insta_link', models.CharField(max_length=100, null=True)),
                ('twitter_link', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club_Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('featured_image', models.ImageField(default='album/default.jpg', null=True, upload_to='album')),
                ('date', models.DateField(null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name_display', models.CharField(max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='user_pfps/default.jpg', null=True, upload_to='user_pfps')),
                ('content_creator', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
                ('social_link', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('featured_image', models.ImageField(default='shop/product_default.jpg', null=True, upload_to='shop')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('product_information', ckeditor.fields.RichTextField(null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise_Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('size_option', models.BooleanField(default=False, null=True)),
                ('unique_player', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flag', models.ImageField(default='flags/Germany.jpg', null=True, upload_to='flags')),
            ],
        ),
        migrations.CreateModel(
            name='News_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads')),
                ('post_content', ckeditor.fields.RichTextField()),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('excerpt', models.TextField(null=True)),
                ('featured', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customuser')),
                ('news_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article_type')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('address_1', models.CharField(blank=True, max_length=200, null=True)),
                ('address_2', models.CharField(blank=True, max_length=200, null=True)),
                ('postcode', models.BigIntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('order_notes', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('packaging', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(max_length=100)),
                ('dispatched', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('second_name', models.CharField(max_length=100, null=True)),
                ('kit_no', models.IntegerField(null=True)),
                ('nationality', django_countries.fields.CountryField(max_length=2, null=True)),
                ('profile_pic', models.ImageField(default='players/player-placeholder-380x570.jpg', null=True, upload_to='players')),
                ('height', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('past_club', models.CharField(max_length=100, null=True)),
                ('born', models.DateField(null=True)),
                ('contract_end', models.DateField(null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('profile_banner', models.ImageField(default='players/default_banner.jpg', null=True, upload_to='players')),
                ('biography', ckeditor.fields.RichTextField(null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=100, null=True)),
                ('logo', models.ImageField(default='logos/sponsor_default.png', null=True, upload_to='logos')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('nationality', django_countries.fields.CountryField(max_length=2, null=True)),
                ('profile_pic', models.ImageField(default='players/player-placeholder-380x570.jpg', null=True, upload_to='players')),
                ('age', models.IntegerField(null=True)),
                ('previous_post', models.CharField(max_length=100, null=True)),
                ('short_name', models.CharField(max_length=10, null=True)),
                ('born', models.DateField(null=True)),
                ('contract_start', models.DateField(null=True)),
                ('contract_end', models.DateField(null=True)),
                ('biography', ckeditor.fields.RichTextField(null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(default='logos/default_logo.png', null=True, upload_to='logos')),
                ('color', models.CharField(max_length=50, null=True)),
                ('alt_color', models.CharField(max_length=50, null=True)),
                ('manager', models.CharField(max_length=100, null=True)),
                ('league_side', models.BooleanField(default=True)),
                ('ucl_side', models.BooleanField(default=False)),
                ('pokal_side', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player_Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apps', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('yellows', models.IntegerField(default=0)),
                ('reds', models.IntegerField(default=0)),
                ('own_goals', models.IntegerField(default=0)),
                ('fouls', models.IntegerField(default=0)),
                ('offsides', models.IntegerField(default=0)),
                ('ppg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('win_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('motm', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.season')),
            ],
        ),
        migrations.CreateModel(
            name='Player_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='gallery/player/default.png', null=True, upload_to='gallery/player')),
                ('date', models.DateField(null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.position'),
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('parent_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.player')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.merchandise')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.merchandise_size')),
            ],
        ),
        migrations.CreateModel(
            name='News_Tag_Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.news_article')),
                ('staff_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
            ],
        ),
        migrations.CreateModel(
            name='News_Tag_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.news_article')),
                ('player_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
        ),
        migrations.AddField(
            model_name='merchandise_size',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.merchandise_type'),
        ),
        migrations.CreateModel(
            name='Merchandise_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.merchandise')),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(default='shop/product_default.jpg', null=True, upload_to='shop')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.merchandise')),
            ],
        ),
        migrations.AddField(
            model_name='merchandise',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.merchandise_type'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customuser')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.comment')),
                ('parent_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.news_article')),
            ],
        ),
        migrations.CreateModel(
            name='Club_season_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(null=True)),
                ('wins', models.IntegerField(null=True)),
                ('loss', models.IntegerField(null=True)),
                ('draw', models.IntegerField(null=True)),
                ('scored', models.IntegerField(null=True)),
                ('conceded', models.IntegerField(null=True)),
                ('goal_diff', models.IntegerField(null=True)),
                ('points', models.IntegerField(null=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.team')),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Album_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='album/default.jpg', null=True, upload_to='album')),
                ('description', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('parent_album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.club_album')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('billing', 'Billing Address'), ('shipping', 'Shipping Address')], default='billing', max_length=30)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address_1', models.CharField(blank=True, max_length=200, null=True)),
                ('address_2', models.CharField(blank=True, max_length=200, null=True)),
                ('postcode', models.BigIntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customuser')),
            ],
        ),
    ]
