# Generated by Django 4.1.3 on 2022-12-09 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduled_Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_title', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.CharField(max_length=100, null=True)),
                ('at_home', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('summary', models.TextField(null=True)),
                ('banner', models.ImageField(default='banners/Allianz_Arena_wide.jpg', null=True, upload_to='banners')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.competition')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('scheduled_match_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.scheduled_match')),
                ('scored', models.IntegerField(null=True)),
                ('conceded', models.IntegerField(null=True)),
                ('video_url', models.CharField(max_length=100, null=True)),
                ('pass_acc', models.DecimalField(decimal_places=1, default=0, max_digits=3, null=True)),
                ('shot_acc', models.DecimalField(decimal_places=1, default=0, max_digits=3, null=True)),
                ('offsides', models.IntegerField(default=0, null=True)),
                ('fouls', models.IntegerField(default=0, null=True)),
                ('shots', models.IntegerField(default=0, null=True)),
                ('shots_target', models.IntegerField(default=0, null=True)),
                ('yellows', models.IntegerField(default=0, null=True)),
                ('reds', models.IntegerField(default=0, null=True)),
                ('corners', models.IntegerField(default=0, null=True)),
                ('saves', models.IntegerField(default=0, null=True)),
                ('possession', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('pass_acc_opp', models.DecimalField(decimal_places=1, default=0, max_digits=3, null=True)),
                ('shot_acc_opp', models.DecimalField(decimal_places=1, default=0, max_digits=3, null=True)),
                ('offsides_opp', models.IntegerField(default=0, null=True)),
                ('fouls_opp', models.IntegerField(default=0, null=True)),
                ('shots_opp', models.IntegerField(default=0, null=True)),
                ('shots_target_opp', models.IntegerField(default=0, null=True)),
                ('yellows_opp', models.IntegerField(default=0, null=True)),
                ('reds_opp', models.IntegerField(default=0, null=True)),
                ('corners_opp', models.IntegerField(default=0, null=True)),
                ('saves_opp', models.IntegerField(default=0, null=True)),
            ],
            bases=('main.scheduled_match',),
        ),
        migrations.CreateModel(
            name='Opponent_Goalscorers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('minute', models.IntegerField(null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match')),
            ],
        ),
        migrations.CreateModel(
            name='Match_timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeside', models.BooleanField(default=True)),
                ('minute', models.IntegerField(null=True)),
                ('who', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match_event')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match')),
            ],
        ),
        migrations.CreateModel(
            name='Goalscorers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField(null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match')),
            ],
        ),
    ]
