# Generated by Django 4.1.4 on 2022-12-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_article',
            name='image_url',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='user_pfps/default.jpg', upload_to='user_pfps'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
