# Generated by Django 4.1.4 on 2022-12-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_article_image_url_alter_customuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_article',
            name='image_url',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
