# Generated by Django 4.1.3 on 2022-11-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_merchandise_merchandise_type_merchandise_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise_size',
            name='size',
        ),
    ]
