# Generated by Django 4.1.2 on 2022-11-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_article',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
    ]
