# Generated by Django 4.1.2 on 2022-11-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_article',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='news_article',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
