# Generated by Django 4.1.3 on 2022-12-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customuser_social_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_article',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
