# Generated by Django 4.1.4 on 2022-12-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_news_article_related_news_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
