# Generated by Django 4.1.3 on 2022-11-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_merchandise_size_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise_type',
            name='size',
        ),
        migrations.AddField(
            model_name='merchandise_size',
            name='size',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
