# Generated by Django 4.1.4 on 2022-12-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_news_article_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bayern',
        ),
        migrations.DeleteModel(
            name='Nationality',
        ),
        migrations.AlterField(
            model_name='news_article',
            name='image_url',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
