# Generated by Django 4.1.3 on 2022-11-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_merchandise_type_size_merchandise_size_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='featured_image',
            field=models.ImageField(default='shop/product_default.jpg', null=True, upload_to='shop'),
        ),
    ]
