# Generated by Django 4.1.4 on 2023-01-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_team_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='related_products',
            field=models.ManyToManyField(blank=True, default=None, to='main.merchandise'),
        ),
    ]
