# Generated by Django 4.1.3 on 2022-12-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news_article_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_type',
            name='css_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
