# Generated by Django 4.1.3 on 2022-11-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_merchandise_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
