# Generated by Django 4.1.2 on 2022-11-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_competition_match_match_event_player_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='corners_opp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='fouls_opp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='offsides_opp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='pass_acc_opp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='reds_opp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='saves_opp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='shot_acc_opp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='shots_opp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='shots_target_opp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='yellows_opp',
            field=models.IntegerField(null=True),
        ),
    ]
