# Generated by Django 4.1.3 on 2022-12-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_article_type_css_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_type',
            name='category',
            field=models.SmallIntegerField(default=1),
        ),
    ]
