# Generated by Django 4.1.4 on 2022-12-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_bayern_delete_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_banner',
            field=models.ImageField(blank=True, null=True, upload_to='players'),
        ),
    ]
