# Generated by Django 4.1.4 on 2023-01-05 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
