# Generated by Django 4.1.4 on 2022-12-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_player_profile_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match_timeline',
            old_name='homeside',
            new_name='is_bayern_player',
        ),
    ]
