# Generated by Django 4.1.3 on 2022-11-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_merchandise_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise_image',
            name='image_url',
            field=models.ImageField(default='shop/product_default.jpg', null=True, upload_to='shop'),
        ),
    ]
