# Generated by Django 4.1.3 on 2022-12-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_article_type_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='corners',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='corners_opp',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='fouls',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='fouls_opp',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='offsides',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='offsides_opp',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='pass_acc',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='pass_acc_opp',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='reds',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='reds_opp',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='saves',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='saves_opp',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='shot_acc',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='shot_acc_opp',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='shots',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='shots_opp',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='shots_target',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='shots_target_opp',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='yellows',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='yellows_opp',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
