# Generated by Django 4.1.3 on 2022-12-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_match_match_title_alter_match_corners_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bayern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Bayern', max_length=100)),
                ('logo', models.ImageField(default='logos/bayern_logo.png', null=True, upload_to='logos')),
                ('color', models.CharField(max_length=50, null=True)),
                ('alt_color', models.CharField(max_length=50, null=True)),
                ('manager', models.CharField(max_length=100, null=True)),
                ('fb_link', models.CharField(max_length=100, null=True)),
                ('insta_link', models.CharField(max_length=100, null=True)),
                ('twitter_link', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
