# Generated by Django 4.1.2 on 2022-11-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_match_time_team_color_team_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='alt_color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
