# Generated by Django 4.1.3 on 2022-11-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_merchandise_image_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise_type',
            name='size_option',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
