# Generated by Django 4.1.4 on 2022-12-17 07:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_homeside_match_timeline_is_bayern_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('profile_pic', models.ImageField(default='staff/long-placeholder-800x450.jpg', null=True, upload_to='staff')),
                ('biography', ckeditor.fields.RichTextField(null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(default='players/player-placeholder-380x570.jpg', null=True, upload_to='staff'),
        ),
    ]
