# Generated by Django 4.1.4 on 2023-01-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_merchandise_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='album_image',
            name='image_url',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='club_album',
            name='featured_image_url',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='album_image',
            name='image',
            field=models.ImageField(null=True, upload_to='album'),
        ),
        migrations.AlterField(
            model_name='club_album',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='album'),
        ),
    ]
