# Generated by Django 4.1.4 on 2022-12-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_board_member_alter_staff_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_member',
            name='profile_pic',
            field=models.CharField(default='staff/long-placeholder-800x450.jpg', max_length=600),
        ),
    ]
