# Generated by Django 4.1.4 on 2023-01-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_album_image_image_url_club_album_featured_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='album'),
        ),
        migrations.AlterField(
            model_name='club_album',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='album'),
        ),
    ]
