# Generated by Django 4.1.3 on 2022-11-28 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merchandise_type_size_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.address')),
                ('order_notes', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('packaging', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(max_length=100)),
                ('dispatched', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            bases=('main.address',),
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('size', models.CharField(max_length=100, null=True)),
                ('parent_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.merchandise')),
            ],
        ),
    ]
