# Generated by Django 4.1.4 on 2022-12-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_board_member_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_member',
            name='board_type',
            field=models.CharField(choices=[('ag', 'AG'), ('ev', 'eV')], default='ag', max_length=5),
        ),
    ]
