# Generated by Django 4.1.2 on 2022-11-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_opponent_goalscorers'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='summary',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='video_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match_timeline',
            name='homeside',
            field=models.BooleanField(default=True),
        ),
    ]
