# Generated by Django 4.1.3 on 2022-11-28 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_order_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.player'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.merchandise_size'),
        ),
    ]
