# Generated by Django 4.1.4 on 2023-01-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_album_image_date_alter_album_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match_timeline',
            name='match',
        ),
        migrations.RemoveField(
            model_name='match_timeline',
            name='name',
        ),
        migrations.RemoveField(
            model_name='opponent_goalscorers',
            name='match',
        ),
        migrations.DeleteModel(
            name='Goalscorers',
        ),
        migrations.DeleteModel(
            name='Match_timeline',
        ),
        migrations.DeleteModel(
            name='Opponent_Goalscorers',
        ),
    ]
