# Generated by Django 4.1.3 on 2022-11-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_order_item_player_alter_order_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
