# Generated by Django 4.1.2 on 2022-11-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_match_summary_match_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_timeline',
            name='homeside',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
