# Generated by Django 4.1.4 on 2022-12-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_board_member_board_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trophies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.SmallIntegerField(blank=True, null=True)),
                ('image', models.CharField(default='trophies/placeholder-210x210.png', max_length=600)),
            ],
        ),
    ]
