# Generated by Django 4.1.4 on 2023-01-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_match_timeline_match_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
