# Generated by Django 4.1.4 on 2022-12-17 20:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_trophies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mini_Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sub_heading', models.CharField(blank=True, max_length=100, null=True)),
                ('board_type', models.CharField(choices=[('mem', 'Membership'), ('venue', 'Venue'), ('past_mem', 'Honoured Members'), ('hof', 'Hall of Fame'), ('milestone', 'MileStones')], max_length=20, null=True)),
                ('banner', models.CharField(default='/media/article/default-banner-800x450.png', max_length=600)),
                ('content', ckeditor.fields.RichTextField(null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='board_member',
            name='profile_pic',
            field=models.CharField(default='/media/staff/long-placeholder-800x450.jpg', max_length=600),
        ),
        migrations.AlterField(
            model_name='trophies',
            name='image',
            field=models.CharField(default='/media/trophies/placeholder-210x210.png', max_length=600),
        ),
    ]
