# Generated by Django 4.1.3 on 2022-11-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_address_address_address_address_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='parent_order',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='player',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='size',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_Item',
        ),
    ]
