# Generated by Django 4.1.4 on 2023-01-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_delete_match'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scheduled_Match',
        ),
    ]
