# Generated by Django 4.1.4 on 2022-12-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_mini_articles_alter_board_member_profile_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mini_articles',
            old_name='board_type',
            new_name='category',
        ),
    ]
