# Generated by Django 4.1.2 on 2022-11-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_match_timeline_homeside'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(default='logos/default_logo.png', null=True, upload_to='logos'),
        ),
    ]
