# Generated by Django 4.1.4 on 2022-12-18 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_board_type_mini_articles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_article',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to='main.customuser'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='main.customuser'),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.news_article')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customuser')),
            ],
        ),
    ]
