# Generated by Django 4.1.4 on 2023-01-06 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_scheduled_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_title', models.CharField(max_length=50)),
                ('venue', models.CharField(blank=True, max_length=50, null=True)),
                ('at_home', models.BooleanField(default=True)),
                ('finished', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
                ('time', models.DateTimeField(null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('banner', models.ImageField(default='banners/Allianz_Arena_wide.jpg', null=True, upload_to='banners')),
                ('scored', models.PositiveSmallIntegerField(default=0, null=True)),
                ('conceded', models.PositiveSmallIntegerField(default=0, null=True)),
                ('video_url', models.CharField(blank=True, max_length=200, null=True)),
                ('pass_acc', models.DecimalField(decimal_places=1, default=0, max_digits=3, null=True)),
                ('shot_acc', models.DecimalField(decimal_places=1, default=0, max_digits=3, null=True)),
                ('offsides', models.PositiveSmallIntegerField(default=0, null=True)),
                ('fouls', models.PositiveSmallIntegerField(default=0, null=True)),
                ('shots', models.PositiveSmallIntegerField(default=0, null=True)),
                ('shots_target', models.PositiveSmallIntegerField(default=0, null=True)),
                ('yellows', models.PositiveSmallIntegerField(default=0, null=True)),
                ('reds', models.PositiveSmallIntegerField(default=0, null=True)),
                ('corners', models.PositiveSmallIntegerField(default=0, null=True)),
                ('saves', models.PositiveSmallIntegerField(default=0, null=True)),
                ('possession', models.DecimalField(decimal_places=1, default=50, max_digits=3, null=True)),
                ('pass_acc_opp', models.DecimalField(decimal_places=1, default=0, max_digits=3, null=True)),
                ('shot_acc_opp', models.DecimalField(decimal_places=1, default=0, max_digits=3, null=True)),
                ('offsides_opp', models.PositiveSmallIntegerField(default=0, null=True)),
                ('fouls_opp', models.PositiveSmallIntegerField(default=0, null=True)),
                ('shots_opp', models.PositiveSmallIntegerField(default=0, null=True)),
                ('shots_target_opp', models.PositiveSmallIntegerField(default=0, null=True)),
                ('yellows_opp', models.PositiveSmallIntegerField(default=0, null=True)),
                ('reds_opp', models.PositiveSmallIntegerField(default=0, null=True)),
                ('corners_opp', models.PositiveSmallIntegerField(default=0, null=True)),
                ('saves_opp', models.PositiveSmallIntegerField(default=0, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.competition')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.AlterField(
            model_name='match_event',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Opponent_Goalscorers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('minute', models.PositiveSmallIntegerField(null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match')),
            ],
        ),
        migrations.CreateModel(
            name='Match_timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bayern_player', models.BooleanField(default=True)),
                ('minute', models.PositiveSmallIntegerField(null=True)),
                ('who', models.CharField(blank=True, max_length=100, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match_event')),
            ],
        ),
        migrations.CreateModel(
            name='Goalscorers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveSmallIntegerField(null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.player')),
            ],
        ),
    ]
