# Generated by Django 4.1.4 on 2022-12-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_news_article_liked_alter_news_article_author_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_article',
            name='video_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
