# Generated by Django 4.1.4 on 2023-01-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_match_conceded_alter_match_corners_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('display', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='news_article',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news_article',
            name='tags',
            field=models.ManyToManyField(default=None, to='main.news_tag'),
        ),
    ]
