# Generated by Django 4.1.4 on 2022-12-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_news_article_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='video_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
