# Generated by Django 4.1.4 on 2022-12-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_match_video_url_alter_news_article_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_article',
            name='image_url',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
