# Generated by Django 4.1.4 on 2023-01-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_match_tags_alter_news_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='tags',
        ),
        migrations.AddField(
            model_name='match',
            name='news_tags',
            field=models.ManyToManyField(blank=True, default=None, to='main.news_article'),
        ),
    ]
