# Generated by Django 4.1.4 on 2023-01-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_match_tags_match_news_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_article',
            name='home_banner',
            field=models.BooleanField(default=False),
        ),
    ]
