# Generated by Django 4.1.4 on 2023-01-08 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_match_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('join', 'Joined'), ('exit', 'Left'), ('injury', 'Injury'), ('award', 'Award')], default='join', max_length=10, null=True)),
                ('description', models.TextField(max_length=300)),
                ('date', models.DateField()),
                ('player', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='main.player')),
                ('staff', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
            ],
        ),
    ]
