# Generated by Django 4.1.4 on 2023-01-08 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='player',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.player'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='staff',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.staff'),
        ),
    ]
