# Generated by Django 4.1.4 on 2023-01-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_social_media_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_tag_staff',
            name='news',
        ),
        migrations.RemoveField(
            model_name='news_tag_staff',
            name='staff_tag',
        ),
        migrations.DeleteModel(
            name='News_Tag_Player',
        ),
        migrations.DeleteModel(
            name='News_Tag_Staff',
        ),
    ]
