# Generated by Django 4.1.4 on 2023-01-08 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_player_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
    ]
