# Generated by Django 4.1.4 on 2023-01-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_order_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Direct Bank Transfer'), ('upi', 'UPI Payment'), ('cod', 'Cash on Delivery')], default='cod', max_length=100),
        ),
    ]
