# Generated by Django 4.1.4 on 2023-01-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_order_company_alter_order_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Direct Bank Transfer'), ('upi', 'UPI Payment'), ('cod', 'Cash on Delivery')], default='cod', max_length=5),
        ),
    ]
