# Generated by Django 4.1.4 on 2023-01-10 06:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_order_order_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='biography',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='born',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contract_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contract_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='previous_post',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
