# Generated by Django 4.1.4 on 2023-01-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_player_age_alter_player_biography_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='content_creator',
        ),
        migrations.AlterField(
            model_name='article_type',
            name='css_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article_type',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user_pfps/default.jpg', upload_to='user_pfps'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
