# Generated by Django 4.1.4 on 2023-01-11 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_customuser_content_creator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets_Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_1_seats', models.PositiveIntegerField()),
                ('cat_2_seats', models.PositiveIntegerField()),
                ('cat_3_seats', models.PositiveIntegerField()),
                ('cat_4_seats', models.PositiveIntegerField()),
                ('cat_5_seats', models.PositiveIntegerField()),
                ('match', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.match')),
            ],
        ),
        migrations.CreateModel(
            name='Sold_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_cat', models.CharField(choices=[('cat_1', 'Category 1'), ('cat_2', 'Category 2'), ('cat_3', 'Category 3'), ('cat_4', 'Category 4'), ('cat_5', 'Category 5')], default='cat_3', max_length=5, null=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('match', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tickets_collection')),
                ('who', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customuser')),
            ],
        ),
    ]
