# Generated by Django 4.1.4 on 2023-01-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_tickets_collection_sold_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets_collection',
            name='cat_1_price',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='tickets_collection',
            name='cat_2_price',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='tickets_collection',
            name='cat_3_price',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AddField(
            model_name='tickets_collection',
            name='cat_4_price',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='tickets_collection',
            name='cat_5_price',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
