# Generated by Django 4.1.4 on 2023-01-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_tickets_collection_cat_1_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold_ticket',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Direct Bank Transfer'), ('upi', 'UPI Payment'), ('cod', 'Cash on Delivery')], default='cod', max_length=8),
        ),
        migrations.AddField(
            model_name='sold_ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
