# Generated by Django 4.1.4 on 2023-01-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_sold_ticket_payment_method_sold_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='booking_open',
            field=models.BooleanField(default=False),
        ),
    ]
