# Generated by Django 4.1.4 on 2023-01-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_match_booking_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
