# Generated by Django 4.1.4 on 2023-01-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_contact_us_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='born',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=6, max_digits=3),
        ),
    ]
