# Generated by Django 4.1.4 on 2023-01-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_player_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=6, max_digits=3, null=True),
        ),
    ]
