# Generated by Django 4.1.4 on 2023-01-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_player_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_image',
            name='image_url',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='player_image',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player_image',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='player_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/player'),
        ),
    ]
