# Generated by Django 4.1.4 on 2023-01-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_player_image_image_url_alter_player_image_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_stats',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=6, max_digits=3),
        ),
    ]
