# Generated by Django 4.1.4 on 2023-01-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_player_stats_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophies',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='article_type',
            name='category',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='club_season_stats',
            name='conceded',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='club_season_stats',
            name='draw',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='club_season_stats',
            name='goal_diff',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='club_season_stats',
            name='loss',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='club_season_stats',
            name='played',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='club_season_stats',
            name='points',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='club_season_stats',
            name='scored',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='club_season_stats',
            name='wins',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='discount',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='kit_no',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='apps',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='assists',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='fouls',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='goals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='motm',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='offsides',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='own_goals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='reds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='yellows',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trophies',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
