# Generated by Django 4.1.2 on 2022-11-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_match_corners_opp_match_fouls_opp_match_offsides_opp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goalscorers',
            name='minute',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='conceded',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='corners',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='fouls',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='offsides',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='pass_acc',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='pass_acc_opp',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='possession',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='reds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='saves',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='scored',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='shot_acc',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='shot_acc_opp',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='shots',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='shots_target',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='yellows',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match_timeline',
            name='minute',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match_timeline',
            name='who',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos'),
        ),
    ]
