# Generated by Django 4.1.2 on 2022-11-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_match_timeline_homeside'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
