# Generated by Django 4.1.2 on 2022-11-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_match_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_article',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
