# Generated by Django 4.1.2 on 2022-11-04 09:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_news_article_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flag', models.ImageField(default='flags/Germany.jpg', null=True, upload_to='flags')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='biography',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='born',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='contract_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='past_club',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('1', 'Goalkeepers'), ('2', 'Defenders'), ('3', 'Midfielders'), ('4', 'Forwards')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='profile_banner',
            field=models.ImageField(default='players/default_banner.jpg', null=True, upload_to='players'),
        ),
        migrations.AddField(
            model_name='player',
            name='profile_pic',
            field=models.ImageField(default='players/default.jpg', null=True, upload_to='players'),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Player_Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apps', models.CharField(max_length=20)),
                ('minutes', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('yellows', models.IntegerField()),
                ('reds', models.IntegerField()),
                ('own_goals', models.IntegerField()),
                ('fouls', models.IntegerField()),
                ('offsides', models.IntegerField()),
                ('ppg', models.IntegerField()),
                ('win_ratio', models.IntegerField()),
                ('motm', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.season')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nationality'),
        ),
    ]
