# Generated by Django 4.1.2 on 2022-11-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_nationality_season_player_age_player_biography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Goalkeepers', 'Goalkeepers'), ('Defenders', 'Defenders'), ('Midfielders', 'Midfielders'), ('Forwards', 'Forwards')], default='Goalkeepers', max_length=20),
        ),
    ]
