# Generated by Django 4.1.2 on 2022-11-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
