# Generated by Django 4.1.2 on 2022-11-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_player_first_name_player_second_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
