# Generated by Django 4.1.2 on 2022-11-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_player_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='kit_no',
            field=models.IntegerField(null=True),
        ),
    ]
