# Generated by Django 4.1.2 on 2022-11-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_player_kit_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_stats',
            name='ppg',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='win_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
