# Generated by Django 4.1.2 on 2022-11-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_player_stats_ppg_alter_player_stats_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
    ]
