# Generated by Django 4.1.2 on 2022-11-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_season_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_stats',
            name='apps',
            field=models.IntegerField(null=True),
        ),
    ]
