# Generated by Django 4.1.2 on 2022-11-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_player_stats_apps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_stats',
            name='apps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='fouls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='motm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='offsides',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='own_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='ppg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='reds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='win_ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='yellows',
            field=models.IntegerField(default=0),
        ),
    ]
