# Generated by Django 4.1.2 on 2022-11-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_player_stats_apps_alter_player_stats_assists_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=100, null=True)),
                ('logo', models.ImageField(default='logos/sponsor_default.png', null=True, upload_to='logos')),
            ],
        ),
    ]
