# Generated by Django 4.1.2 on 2022-11-06 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_sponsor_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='gallery/player/default.png', null=True, upload_to='gallery/player')),
                ('date', models.DateField(null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
        ),
    ]
