# Generated by Django 4.1.2 on 2022-11-06 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_article',
            name='excerpt',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='News_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.news_article')),
                ('player_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
        ),
    ]
