# Generated by Django 4.1.2 on 2022-11-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_news_article_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_pic',
            field=models.ImageField(default='players/player-placeholder-380x570.jpg', null=True, upload_to='players'),
        ),
    ]
