# Generated by Django 4.1.2 on 2022-11-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_player_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_stats',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
    ]
