# Generated by Django 4.1.2 on 2022-11-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_player_stats_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_stats',
            name='slug',
        ),
        migrations.AddField(
            model_name='player',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
    ]
