# Generated by Django 4.1.2 on 2022-11-08 09:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_player_stats_slug_player_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(default='players/player-placeholder-380x570.jpg', null=True, upload_to='players')),
                ('age', models.IntegerField(null=True)),
                ('previous_post', models.CharField(max_length=100, null=True)),
                ('born', models.DateField(null=True)),
                ('contract_start', models.DateField(null=True)),
                ('contract_end', models.DateField(null=True)),
                ('profile_banner', models.ImageField(default='players/default_banner.jpg', null=True, upload_to='players')),
                ('biography', ckeditor.fields.RichTextField(null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nationality')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.position')),
            ],
        ),
    ]
