# Generated by Django 4.1.2 on 2022-11-08 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='position',
        ),
    ]
