# Generated by Django 4.1.2 on 2022-11-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_coach_short_name_alter_coach_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league_side',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='pokal_side',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='ucl_side',
            field=models.BooleanField(default=False),
        ),
    ]
