# Generated by Django 4.1.2 on 2022-11-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_team_league_side_team_pokal_side_team_ucl_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_season_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('played', models.IntegerField(null=True)),
                ('wins', models.IntegerField(null=True)),
                ('loss', models.IntegerField(null=True)),
                ('draw', models.IntegerField(null=True)),
            ],
        ),
    ]
