# Generated by Django 4.1.2 on 2022-11-08 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_club_season_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club_season_stats',
            name='name',
        ),
        migrations.AddField(
            model_name='club_season_stats',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
    ]
