# Generated by Django 4.1.2 on 2022-11-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_remove_club_season_stats_name_club_season_stats_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_season_stats',
            name='conceded',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='club_season_stats',
            name='goal_diff',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='club_season_stats',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='club_season_stats',
            name='scored',
            field=models.IntegerField(null=True),
        ),
    ]
