# Generated by Django 4.1.2 on 2022-11-08 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_club_season_stats_conceded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_season_stats',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.competition'),
        ),
    ]
