# Generated by Django 4.1.2 on 2022-11-09 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_club_season_stats_competition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coach',
            new_name='Staff',
        ),
    ]
