# Generated by Django 4.1.2 on 2022-11-09 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_rename_coach_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('featured_image', models.ImageField(default='album/default.jpg', null=True, upload_to='album')),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='album/default.jpg', null=True, upload_to='album')),
                ('description', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('parent_album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.club_album')),
            ],
        ),
    ]
