# Generated by Django 4.1.2 on 2022-11-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_club_album_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_album',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
    ]
