# Generated by Django 4.1.2 on 2022-11-09 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_club_album_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_tag',
            name='staff_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.staff'),
        ),
        migrations.AlterField(
            model_name='news_tag',
            name='player_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.player'),
        ),
    ]
