# Generated by Django 4.1.2 on 2022-11-09 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_rename_news_tag_news_tag_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_tag_player',
            name='staff_tag',
        ),
        migrations.CreateModel(
            name='News_Tag_Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.news_article')),
                ('staff_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
            ],
        ),
    ]
