# Generated by Django 4.1.2 on 2022-11-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_customuser_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sname',
        ),
    ]
