# Generated by Django 4.1.2 on 2022-11-11 12:49

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_address_city_address_email_address_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
