# Generated by Django 4.1.2 on 2022-11-11 12:57

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_alter_staff_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
